---
- hosts: dev
  become: true
  tasks:
    - name: Install python pip 
      yum:
        name: python3-pip
        state: present
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
    - name: Add docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes
    - name: install docker
      package:
        name: docker-ce
        state: latest
      become: yes
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: my-app
        image: "amarraji/my-app:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
